version: "3.8" # https://docs.docker.com/compose/compose-file/
services:
  app:
    container_name: nikel_core
    restart: always
    build: ./
    environment:
      GIN_MODE: "$GIN_MODE"
      RATE_LIMIT: "$RATE_LIMIT"
      CACHE_EXPIRY: "CACHE_EXPIRY"
    ports:
      - "$PORT:8080"