// DO NOT TOUCH. This file is automatically generated.
package main

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"math"
)

// getServices queries via the services endpoint
func getServices(c *gin.Context) {
	offset := parseInt(c.Query("offset"), 0, math.MaxInt64, 0)
	limit := parseInt(c.Query("limit"), 1, TOPLIMIT, DEFAULTLIMIT)

	data := autoQuery(
		database.ServicesData,
		c.Request.URL.Query(),
		limit,
		offset,
	)

	res, _ := json.Marshal(data)
	var services []Service
	json.Unmarshal(res, &services)
	if len(services) == 0 {
		sendEmptySuccess(c)
	} else {
		sendSuccess(c, services)
	}
}
