// DO NOT TOUCH. This file is automatically generated.
package handlers

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"github.com/nikel-api/nikel/nikel-core/config"
	"github.com/nikel-api/nikel/nikel-core/database"
	"github.com/nikel-api/nikel/nikel-core/query"
	"github.com/nikel-api/nikel/nikel-core/response"
	"math"
)

// GetFood queries via the food endpoint
func GetFood(c *gin.Context) {
	offset := query.ParseInt(c.Query("offset"), 0, math.MaxInt64, 0)
	limit := query.ParseInt(c.Query("limit"), 1, config.TOPLIMIT, config.DEFAULTLIMIT)

	data := query.AutoQuery(
		database.DB.FoodData,
		c.Request.URL.Query(),
		limit,
		offset,
	)

	res, _ := json.Marshal(data)
	var food []database.Food
	json.Unmarshal(res, &food)
	if len(food) == 0 {
		response.SendEmptySuccess(c)
	} else {
		response.SendSuccess(c, food)
	}
}
